import { useState } from 'react';
import { Bot, CheckCircle2, ChevronRight, FileText as FileSparkles, Sparkles, WandSparkles } from 'lucide-react';
import { api } from '../services/api.js';

export function AIAnalysisPanel({ company, onCompanyChange }) {
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[site,setSite]=useState(null);
  const analysis=company.analysis;
  const analyze=async()=>{setBusy('analyze');setError('');try{const result=await api(`/companies/${company._id}/analyze`,{method:'POST'});onCompanyChange(result.company)}catch(e){setError(e.message)}finally{setBusy('')}};
  const generate=async()=>{setBusy('generate');setError('');try{const result=await api(`/companies/${company._id}/generate-site`,{method:'POST'});setSite(result.site);onCompanyChange(result.company)}catch(e){setError(e.message)}finally{setBusy('')}};
  return <section className="ai-workspace"><div className="ai-heading"><div className="ai-title"><span><Bot/></span><div><span className="eyebrow">Assistente estratégico</span><h2>Análise e geração com IA</h2></div></div><div className="ai-actions"><button type="button" className="button button--ai-secondary" onClick={analyze} disabled={Boolean(busy)}><Sparkles size={17}/>{busy==='analyze'?'Analisando...':analysis?'Analisar novamente':'Analisar com IA'}</button><button type="button" className="button button--ai" onClick={generate} disabled={Boolean(busy)||!analysis}><WandSparkles size={17}/>{busy==='generate'?'Gerando...':'Gerar site com IA'}</button></div></div>{error&&<div className="ai-error">{error}</div>}{site&&<div className="generation-success"><CheckCircle2/><div><strong>Conteúdo do site gerado</strong><span>{site.name} foi criado como rascunho usando um template controlado.</span></div><span className="site-id">ID {site._id.slice(-6)}</span></div>}{!analysis?<div className="ai-empty"><FileSparkles/><div><strong>Transforme os dados em uma estratégia</strong><p>A IA avaliará potencial, posicionamento, template, cores, seções e argumentos para sua abordagem comercial.</p></div></div>:<div className="analysis-content"><div className="score-block"><span>Potencial comercial</span><strong>{analysis.potentialScore}<small>/100</small></strong><div className="score-track"><i style={{width:`${analysis.potentialScore}%`}}/></div></div><div className="analysis-summary"><article><span>Template recomendado</span><strong>{analysis.recommendedTemplate}</strong></article><article><span>Estilo recomendado</span><strong>{analysis.recommendedStyle}</strong></article><article><span>CTA principal</span><strong>{analysis.mainCTA}</strong></article><article><span>Paleta sugerida</span><div className="color-list">{analysis.recommendedColors?.map(color=><i key={color} title={color} style={{background:color}}/>)}</div></article></div><div className="analysis-wide"><article><span>Estrutura recomendada</span><div className="section-flow">{analysis.recommendedSections?.map((section,index)=><span key={section}>{section}{index<analysis.recommendedSections.length-1&&<ChevronRight/>}</span>)}</div></article><article><span>Argumentos para venda</span><ul>{analysis.salesArguments?.map(item=><li key={item}>{item}</li>)}</ul></article><article><span>Melhorias recomendadas</span><ul>{analysis.recommendations?.map(item=><li key={item}>{item}</li>)}</ul></article></div></div>}</section>;
}
