import { useEffect, useState } from 'react';
import { CreditCard, LoaderCircle, LockKeyhole } from 'lucide-react';
import { api } from '../services/api.js';

const initial={name:'',email:'',cpfCnpj:'',phone:''};
export function CheckoutPanel({siteSlug,existingOrderToken=''}){const[form,setForm]=useState(initial),[order,setOrder]=useState(existingOrderToken?{orderId:existingOrderToken}:null),[status,setStatus]=useState(''),[subscriptionStatus,setSubscriptionStatus]=useState(''),[subscriptionCheckout,setSubscriptionCheckout]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!order?.orderId||['failed','canceled','refunded'].includes(status)||status==='published'&&subscriptionStatus==='active')return undefined;const load=()=>api(`/public/orders/${order.orderId}`).then((data)=>{setStatus(data.status);setSubscriptionStatus(data.subscription?.status||'');}).catch((requestError)=>setError(requestError.message));load();const poll=window.setInterval(load,1500);return()=>window.clearInterval(poll);},[order?.orderId,status,subscriptionStatus]);
  const change=(event)=>setForm((current)=>({...current,[event.target.name]:event.target.value}));
  const submit=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const result=await api('/public/orders',{method:'POST',body:JSON.stringify({...form,siteSlug})});setOrder(result);setStatus(result.status);}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  const mockPay=async()=>{setBusy(true);setError('');try{await api(`/public/orders/${order.orderId}/mock-pay`,{method:'POST'});setStatus('paid');}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  const activateSubscription=async()=>{setBusy(true);setError('');try{const result=await api(`/public/orders/${order.orderId}/subscription-checkout`,{method:'POST'});setSubscriptionCheckout(result);if(result.provider==='mock'){await api(`/public/orders/${order.orderId}/mock-subscribe`,{method:'POST'});}else if(result.checkoutUrl){window.location.assign(result.checkoutUrl);}}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  if(status==='published'&&subscriptionStatus==='active')return <section className="checkout-panel checkout-panel--success"><span>Publicação completa</span><h2>Seu site está no ar.</h2><p>A criação foi confirmada e a manutenção mensal está ativa.</p></section>;
  if(status==='published')return <section className="checkout-panel"><div><span>Site publicado</span><h2>Ative a manutenção mensal</h2><p>Esta etapa mantém hospedagem, suporte e republicação automática ativos.</p></div>{error&&<div className="checkout-error">{error}</div>}<button onClick={activateSubscription} disabled={busy}>{busy?<LoaderCircle/>:<CreditCard/>}{busy?'Ativando...':'Ativar mensalidade'}</button>{subscriptionCheckout?.provider==='mock'&&<small>Confirmação mock em processamento.</small>}</section>;
  if(existingOrderToken&&!status)return <section className="checkout-panel"><LoaderCircle/><p>Consultando seu pedido...</p></section>;
  if(order)return <section className="checkout-panel"><div><span>Checkout preparado</span><h2>Conclua para publicar</h2><p>Criação do site + hospedagem e manutenção mensal.</p></div>{error&&<div className="checkout-error">{error}</div>}{order.provider==='mock'?<button onClick={mockPay} disabled={busy}>{busy?<LoaderCircle/>:<CreditCard/>}Simular pagamento aprovado</button>:<a href={order.checkoutUrl}>Ir para o pagamento seguro <LockKeyhole/></a>}<small>Status: {status||order.status}</small></section>;
  return <form className="checkout-panel" onSubmit={submit}><div><span>Pronto para publicar?</span><h2>Finalize seus dados</h2><p>Primeiro você confirma a criação. A mensalidade será ativada em uma etapa separada e claramente identificada.</p></div>{error&&<div className="checkout-error">{error}</div>}<label>Nome completo<input name="name" required value={form.name} onChange={change}/></label><label>E-mail<input name="email" type="email" required value={form.email} onChange={change}/></label><div><label>CPF ou CNPJ<input name="cpfCnpj" required value={form.cpfCnpj} onChange={change}/></label><label>Telefone<input name="phone" required value={form.phone} onChange={change}/></label></div><button disabled={busy}>{busy?<LoaderCircle/>:<CreditCard/>}{busy?'Preparando...':'Pagar criação e publicar'}</button><small><LockKeyhole/> Pagamento processado em ambiente seguro.</small></form>;
}
