import crypto from 'crypto';
import { env } from '../config/env.js';
import { BillingSubscription } from '../models/BillingSubscription.js';
import { Order } from '../models/Order.js';
import { Payment } from '../models/Payment.js';
import { Site } from '../models/Site.js';
import { WebhookEvent } from '../models/WebhookEvent.js';
import { getBillingProvider } from '../services/billing/index.js';
import { queueWebhookEvent } from '../services/billing/billingJobs.js';
import { AppError } from '../utils/AppError.js';

export async function createOrder(req,res){const site=await Site.findOne({slug:req.body.siteSlug,status:{$nin:['arquivado','suspenso']}});if(!site)throw new AppError('Site não encontrado para checkout.',404);const order=await Order.create({publicToken:crypto.randomBytes(24).toString('hex'),siteId:site._id,status:'pending',customer:{name:req.body.name.trim(),email:req.body.email.trim(),cpfCnpj:req.body.cpfCnpj.replace(/\D/g,''),phone:req.body.phone.replace(/\D/g,'')},creationAmount:Math.round(env.defaultCreationFee*100),monthlyAmount:Math.round(env.defaultMonthlyFee*100),provider:env.billingProvider});await Payment.create({orderId:order._id,provider:env.billingProvider,type:'initial',amount:order.creationAmount,status:'pending'});await BillingSubscription.create({orderId:order._id,siteId:site._id,provider:env.billingProvider,amount:order.monthlyAmount,status:'pending_activation'});try{const returnUrl=`${env.clientUrls[0]}/criar-site?order=${order.publicToken}`;const checkout=await getBillingProvider().createCheckout({order:{...order.toObject(),creationAmount:order.creationAmount/100,monthlyAmount:order.monthlyAmount/100},returnUrl});order.providerCheckoutId=checkout.id;order.checkoutUrl=checkout.url;order.status='awaiting_payment';await order.save();res.status(201).json({orderId:order.publicToken,status:order.status,checkoutUrl:order.checkoutUrl,provider:order.provider});}catch(error){order.status='failed';order.failureReason='Não foi possível criar o checkout.';await order.save();throw error;}}
export async function getOrder(req,res){const order=await Order.findOne({publicToken:req.params.token}).populate('siteId','slug status previewUrl productionUrl');if(!order)throw new AppError('Pedido não encontrado.',404);const subscription=await BillingSubscription.findOne({orderId:order._id}).select('status nextBillingAt graceEndsAt');res.json({status:order.status,subscription:subscription?{status:subscription.status,nextBillingAt:subscription.nextBillingAt,graceEndsAt:subscription.graceEndsAt}:null,amounts:{creation:order.creationAmount,monthly:order.monthlyAmount,currency:order.currency},site:order.siteId?{slug:order.siteId.slug,status:order.siteId.status,url:order.siteId.productionUrl||order.siteId.previewUrl}:null});}
export async function mockPayOrder(req,res){if(env.billingProvider!=='mock')throw new AppError('Simulação disponível somente com BILLING_PROVIDER=mock.',404);const order=await Order.findOne({publicToken:req.params.token});if(!order)throw new AppError('Pedido não encontrado.',404);const event=await WebhookEvent.create({provider:'mock',providerEventId:`mock_evt_${crypto.randomUUID()}`,eventType:'CHECKOUT_PAID',payload:{checkout:{id:order.providerCheckoutId,externalReference:String(order._id)}}});await queueWebhookEvent(event._id);res.json({status:'processing'});}
export async function createSubscriptionCheckout(req,res){const order=await Order.findOne({publicToken:req.params.token});if(!order)throw new AppError('Pedido não encontrado.',404);if(!['paid','publishing','published'].includes(order.status))throw new AppError('Confirme primeiro o pagamento da criação.',409);const subscription=await BillingSubscription.findOne({orderId:order._id});if(subscription?.status==='active')return res.json({status:'active'});if(order.subscriptionCheckoutUrl)return res.json({status:'pending_activation',checkoutUrl:order.subscriptionCheckoutUrl,provider:order.provider});const checkout=await getBillingProvider().createSubscriptionCheckout({order:{...order.toObject(),monthlyAmount:order.monthlyAmount/100},returnUrl:`${env.clientUrls[0]}/criar-site?order=${order.publicToken}`});order.providerSubscriptionCheckoutId=checkout.id;order.subscriptionCheckoutUrl=checkout.url;await order.save();res.status(201).json({status:'pending_activation',checkoutUrl:checkout.url,provider:order.provider});}
export async function mockSubscribeOrder(req,res){if(env.billingProvider!=='mock')throw new AppError('Simulação disponível somente em mock.',404);const order=await Order.findOne({publicToken:req.params.token});if(!order)throw new AppError('Pedido não encontrado.',404);const event=await WebhookEvent.create({provider:'mock',providerEventId:`mock_sub_evt_${crypto.randomUUID()}`,eventType:'CHECKOUT_PAID',payload:{checkout:{id:order.providerSubscriptionCheckoutId,externalReference:`subscription:${order._id}`,subscription:{id:`mock_sub_${crypto.randomUUID()}`}}}});await queueWebhookEvent(event._id);res.json({status:'processing'});}
