const palettes = {
  barbearia: ['#12343B', '#682E3C', '#C2A15F', '#DCE8E8'], restaurante: ['#175A78', '#D94732', '#547A4A', '#F2C14E'],
  oficina: ['#111827', '#F97316', '#F8FAFC'], loja: ['#4F46E5', '#EC4899', '#FFFFFF'],
  clínica: ['#314B6B', '#8E82B8', '#91AA9D', '#E58D7B'], clinica: ['#314B6B', '#8E82B8', '#91AA9D', '#E58D7B'],
};
const normalize = (value='') => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const category = (company) => Object.keys(palettes).find((key) => normalize(company.segment).includes(normalize(key))) || 'loja';
const whatsappLink = (company) => company.whatsapp ? `https://wa.me/${company.whatsapp.replace(/\D/g,'')}` : '#contato';

export class MockAIProvider {
  async analyze(company, templates) {
    const type = category(company); const template = templates.find((item) => normalize(item.category).includes(normalize(type))) || templates[0];
    const score = Math.min(96, 62 + (!company.hasWebsite ? 18 : 0) + (company.whatsapp ? 6 : 0) + (company.instagram ? 4 : 0) + (company.services?.length ? 5 : 0));
    return { potentialScore:score, recommendedTemplate:template?.slug || type, recommendedStyle:'moderno, confiável e direto', recommendedColors:palettes[type], recommendedSections:['hero','sobre','servicos','diferenciais','cta','localizacao','horario','contato'], mainCTA:company.whatsapp?'Fale pelo WhatsApp':'Entre em contato', businessDescription:company.description || `${company.name} oferece ${company.segment.toLowerCase()} em ${company.city || 'sua região'}.`, recommendations:['Destacar os principais serviços logo no início','Facilitar o contato em dispositivos móveis','Reforçar localização e horário de atendimento'], salesArguments:['Um site profissional aumenta a confiança antes do primeiro contato','O acesso rápido ao WhatsApp reduz o caminho até o orçamento','A presença própria melhora a apresentação nos resultados de busca'] };
  }
  async generateContent(company, analysis) {
    const type=category(company);
    const voice=type==='barbearia'?{title:`Seu estilo, bem cuidado.`,service:'Veja como funciona',diff:[{title:'Conversa antes do corte',description:'O atendimento começa entendendo o resultado que você procura.'},{title:'Acabamento sem atalhos',description:'Cada detalhe recebe o tempo necessário antes de você sair da cadeira.'}],cta:'Escolha um horário',ctaText:'Fale direto com a equipe e consulte os horários disponíveis.'}:type==='restaurante'?{title:`Tem lugar à mesa.`,service:'Preparado por aqui',diff:[{title:'O cardápio fala por nós',description:'Conheça os sabores e escolha o que combina com o seu momento.'},{title:'Informação sem rodeios',description:'Horários, endereço e formas de pedir sempre fáceis de encontrar.'}],cta:'Vai pedir ou vem pra mesa?',ctaText:'Chame a equipe para consultar o cardápio, fazer um pedido ou reservar.'}:type==='clínica'||type==='clinica'?{title:`Cuidado com clareza, desde o primeiro contato.`,service:'Saiba mais sobre este atendimento',diff:[{title:'Primeiro contato',description:'Fale com a equipe e explique brevemente o que você precisa.'},{title:'Orientação sobre o atendimento',description:'Receba informações sobre horários e próximos passos antes da consulta.'}],cta:'Tire suas dúvidas antes de agendar',ctaText:'Converse com a equipe para entender horários e como funciona o atendimento.'}:{title:company.name,service:'Consulte os detalhes com nossa equipe',diff:[{title:'Contato direto',description:'Fale com quem entende do atendimento.'},{title:'Informações claras',description:'Encontre o que precisa sem perder tempo.'}],cta:'Fale com a equipe',ctaText:'Consulte disponibilidade e outras informações pelo WhatsApp.'};
    const services=(company.services?.length?company.services:[company.segment]).map((title)=>({title,description:voice.service}));
    return { hero:{eyebrow:company.segment,title:voice.title,subtitle:company.description||analysis.businessDescription,ctaLabel:analysis.mainCTA,ctaLink:whatsappLink(company)},about:{title:`Sobre ${company.name}`,text:company.description||analysis.businessDescription},services,differentiators:voice.diff,gallery:{title:type==='restaurante'?'Da cozinha e da casa':'Veja de perto',images:company.photos||[]},cta:{title:voice.cta,text:voice.ctaText,buttonLabel:analysis.mainCTA,buttonLink:whatsappLink(company)},location:{title:'Onde estamos',address:company.address||[company.city,company.state].filter(Boolean).join(' - '),mapsUrl:company.googleMaps||''},hours:{title:'Horário de atendimento',text:company.businessHours||'Consulte os horários disponíveis com a equipe.'},contact:{phone:company.phone||'',whatsapp:company.whatsapp||'',instagram:company.instagram||''},footer:{text:`© ${new Date().getFullYear()} ${company.name}.`},seo:{title:`${company.name} | ${company.segment}${company.city?` em ${company.city}`:''}`,metaDescription:`${company.name}: ${company.segment.toLowerCase()}${company.city?` em ${company.city}`:''}. Consulte informações e entre em contato.`.slice(0,160),keywords:[company.name,company.segment,company.city].filter(Boolean)} };
  }
}
