import { BillingJob } from '../../models/BillingJob.js';
import { BillingSubscription } from '../../models/BillingSubscription.js';
import { Order } from '../../models/Order.js';
import { Payment } from '../../models/Payment.js';
import { Site } from '../../models/Site.js';
import { WebhookEvent } from '../../models/WebhookEvent.js';
import { getDeploymentService } from '../deployment/index.js';

const addDays=(date,days)=>new Date(new Date(date).getTime()+days*86400000);
async function enqueue(type,data={}){const job=await BillingJob.create({type,...data});scheduleBillingJob(job._id);return job;}

async function publish(orderId,siteId){const order=await Order.findById(orderId),site=await Site.findById(siteId).populate('companyId').populate('templateId');if(!order||!site)return;order.status='publishing';await order.save();const deployment=await getDeploymentService().deploy(site);site.status='publicado';site.deploymentId=deployment.deploymentId;site.previewUrl=deployment.previewUrl;site.productionUrl=deployment.productionUrl||'';site.publication={subdomain:deployment.subdomain,version:deployment.version,publishedAt:deployment.deployedAt};await site.save();order.status='published';order.publishedAt=new Date();await order.save();}
async function suspend(siteId){await Site.updateOne({_id:siteId},{$set:{status:'suspenso'}});}

async function processWebhook(webhookEventId){const event=await WebhookEvent.findOneAndUpdate({_id:webhookEventId,status:'pending'},{$set:{status:'processing'},$inc:{attempts:1}},{new:true});if(!event)return;const entity=event.payload.payment||event.payload.checkout||{},externalReference=String(entity.externalReference||event.payload.externalReference||''),subscriptionCheckout=externalReference.startsWith('subscription:'),orderReference=subscriptionCheckout?externalReference.slice(13):externalReference;const order=orderReference?await Order.findById(orderReference).catch(()=>null):null;if(!order){event.status='processed';event.processedAt=new Date();event.errorMessage='Pedido não relacionado.';await event.save();return;}
  const subscription=await BillingSubscription.findOne({orderId:order._id});const type=event.eventType;
  if(['CHECKOUT_PAID','PAYMENT_CONFIRMED','PAYMENT_RECEIVED'].includes(type)){const isInitial=!order.paidAt&&!subscriptionCheckout;if(isInitial){order.status='paid';order.paidAt=new Date();await order.save();await Payment.findOneAndUpdate({orderId:order._id,type:'initial'},{$set:{status:type==='PAYMENT_RECEIVED'?'received':'confirmed',providerPaymentId:entity.id||'',confirmedAt:new Date(),...(type==='PAYMENT_RECEIVED'?{receivedAt:new Date()}:{})}},{new:true});await enqueue('publish_site',{orderId:order._id,siteId:order.siteId});}else if(subscription&&(subscriptionCheckout||entity.subscription||type!=='CHECKOUT_PAID')){subscription.status='active';subscription.overdueSince=null;subscription.graceEndsAt=null;subscription.nextBillingAt=addDays(new Date(),30);subscription.providerSubscriptionId=entity.subscription?.id||entity.subscription||subscription.providerSubscriptionId;const wasSuspended=Boolean(subscription.suspendedAt);subscription.suspendedAt=null;await subscription.save();if(wasSuspended)await enqueue('republish_site',{orderId:order._id,siteId:order.siteId});}}
  if(type==='PAYMENT_OVERDUE'&&subscription){subscription.status='past_due';subscription.overdueSince=new Date();subscription.graceEndsAt=addDays(new Date(),7);await subscription.save();}
  if(['PAYMENT_REFUNDED','PAYMENT_CHARGEBACK_REQUESTED'].includes(type)&&subscription){subscription.status='suspended';subscription.suspendedAt=new Date();await subscription.save();await enqueue('suspend_site',{orderId:order._id,siteId:order.siteId});}
  event.status='processed';event.processedAt=new Date();await event.save();
}

export async function processBillingJob(jobId){const job=await BillingJob.findOneAndUpdate({_id:jobId,status:'pending'},{$set:{status:'processing'},$inc:{attempts:1}},{new:true});if(!job)return;try{if(job.type==='process_webhook')await processWebhook(job.webhookEventId);if(job.type==='publish_site'||job.type==='republish_site')await publish(job.orderId,job.siteId);if(job.type==='suspend_site')await suspend(job.siteId);job.status='done';job.completedAt=new Date();await job.save();}catch(error){console.error(`Falha no job de billing ${job._id}:`,error);job.status='failed';job.errorMessage='Falha ao processar operação de billing.';await job.save();}}
export function scheduleBillingJob(jobId){setImmediate(()=>processBillingJob(jobId).catch((error)=>console.error('Falha ao iniciar job de billing:',error)));}
export async function queueWebhookEvent(webhookEventId){return enqueue('process_webhook',{webhookEventId});}
export async function runBillingLifecycle(){const now=new Date(),graceStart=addDays(now,-3),cancelStart=addDays(now,-30);await BillingSubscription.updateMany({status:'past_due',overdueSince:{$lte:graceStart}},{$set:{status:'grace_period'}});const expired=await BillingSubscription.find({status:{$in:['past_due','grace_period']},graceEndsAt:{$lte:now}});for(const item of expired){item.status='suspended';item.suspendedAt=now;await item.save();await enqueue('suspend_site',{orderId:item.orderId,siteId:item.siteId});}await BillingSubscription.updateMany({status:'suspended',overdueSince:{$lte:cancelStart}},{$set:{status:'canceled',canceledAt:now}});}
export async function recoverBillingJobs(){const jobs=await BillingJob.find({status:'pending'}).select('_id').limit(100);jobs.forEach((job)=>scheduleBillingJob(job._id));await runBillingLifecycle();}
