import { useCallback,useEffect,useState } from 'react';
import { Plus,Users } from 'lucide-react';
import { api } from '../services/api.js';
import { currency,dateBR } from '../utils/currency.js';
import { EmptyState,ErrorState,LoadingState } from '../components/PageState.jsx';

const initial={companyId:'',hiringDate:new Date().toISOString().slice(0,10),creationFee:500,monthlyFee:50,status:'ativo',notes:''};
export function ClientsPage(){
  const[data,setData]=useState(null),[companies,setCompanies]=useState([]),[form,setForm]=useState(initial),[show,setShow]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=useCallback(()=>Promise.all([api('/clients'),api('/companies?limit=100')]).then(([clients,businesses])=>{setData(clients);setCompanies(businesses.items.filter(company=>!clients.items.some(client=>client.companyId?._id===company._id)))}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
  const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await api('/clients',{method:'POST',body:JSON.stringify({...form,creationFee:Number(form.creationFee),monthlyFee:Number(form.monthlyFee)})});setForm(initial);setShow(false);load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const status=async(client,value)=>{try{const updated=await api(`/clients/${client._id}`,{method:'PUT',body:JSON.stringify({status:value})});setData(current=>({...current,items:current.items.map(item=>item._id===updated._id?updated:item)}))}catch(e){setError(e.message)}};
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Carteira</span><h1>Clientes</h1><p>Empresas que aceitaram a proposta e seus contratos.</p></div><button className="button button--primary" onClick={()=>setShow(!show)}><Plus size={18}/>Transformar empresa</button></div>{show&&<form className="panel client-form" onSubmit={submit}><label className="span-2">Empresa<select required value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}><option value="">Selecione uma empresa</option>{companies.map(company=><option key={company._id} value={company._id}>{company.name} — {company.segment}</option>)}</select></label><label>Data de contratação<input type="date" required value={form.hiringDate} onChange={e=>setForm({...form,hiringDate:e.target.value})}/></label><label>Valor da criação<input type="number" min="0" step="0.01" value={form.creationFee} onChange={e=>setForm({...form,creationFee:e.target.value})}/></label><label>Mensalidade<input type="number" min="0" step="0.01" value={form.monthlyFee} onChange={e=>setForm({...form,monthlyFee:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ativo</option><option>inativo</option><option>cancelado</option></select></label><label className="span-2">Observações<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="button button--secondary" onClick={()=>setShow(false)}>Cancelar</button><button className="button button--primary" disabled={saving}>{saving?'Salvando...':'Criar cliente'}</button></div></form>}{error&&<ErrorState message={error} onRetry={load}/>} {!data&&!error?<LoadingState/>:data?.items.length?<section className="panel"><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Contratação</th><th>Criação</th><th>Mensalidade</th><th>Status</th></tr></thead><tbody>{data.items.map(client=><tr key={client._id}><td><div className="company-cell"><span><Users size={18}/></span><div><strong>{client.companyId?.name}</strong><small>{client.companyId?.segment}</small></div></div></td><td>{dateBR(client.hiringDate)}</td><td>{currency(client.creationFee)}</td><td><strong>{currency(client.monthlyFee)}</strong></td><td><select className={`inline-status inline-status--${client.status}`} value={client.status} onChange={e=>status(client,e.target.value)}><option>ativo</option><option>inativo</option><option>cancelado</option></select></td></tr>)}</tbody></table></div></section>:data&&<section className="panel"><EmptyState title="Nenhum cliente ainda" text="Transforme uma empresa quando a proposta for aceita."/></section>}</div>;
}
