import { useCallback, useEffect, useState } from 'react';
import { Building2, CircleDollarSign, CreditCard, FileCheck2, FileClock, LayoutTemplate, Plus, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';
import { ErrorState, LoadingState, EmptyState } from '../components/PageState.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { currency } from '../utils/currency.js';

export function DashboardPage(){
  const[data,setData]=useState(null),[error,setError]=useState('');const load=useCallback(()=>{setError('');api('/dashboard').then(setData).catch(e=>setError(e.message));},[]);useEffect(load,[load]);
  if(!data&&!error)return <LoadingState/>;if(error)return <ErrorState message={error} onRetry={load}/>;
  const cards=[[data.metrics.companies,'Empresas cadastradas',Building2,'blue'],[data.metrics.highPotential,'Alto potencial',TrendingUp,'green'],[data.metrics.preparingSites,'Sites em preparação',FileClock,'amber'],[data.metrics.publishedSites,'Sites publicados',FileCheck2,'violet'],[data.metrics.templates,'Templates ativos',LayoutTemplate,'slate'],[data.metrics.activeClients,'Clientes ativos',Users,'green'],[currency(data.metrics.monthlyRevenue),'Receita recorrente',CircleDollarSign,'blue'],[currency(data.metrics.creationRevenue),'Receita de criação',CircleDollarSign,'violet'],[data.metrics.pendingSubscriptions,'Mensalidades pendentes',CreditCard,'amber']];
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Visão geral</span><h1>Dashboard</h1><p>Acompanhe oportunidades, produção e resultados financeiros.</p></div><Link className="button button--primary" to="/empresas/nova"><Plus size={18}/>Nova empresa</Link></div><section className="metric-grid metric-grid--extended">{cards.map(([value,label,Icon,color])=><article className="metric-card" key={label}><span className={`metric-icon metric-icon--${color}`}><Icon/></span><div><strong className={typeof value==='string'?'metric-money':''}>{value}</strong><span>{label}</span></div></article>)}</section><section className="panel"><div className="panel-heading"><div><h2>Recomendadas para contato</h2><p>Empresas priorizadas por potencial e estágio.</p></div><Link to="/empresas">Ver todas</Link></div>{data.recommendations.length?<div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Segmento</th><th>Local</th><th>Potencial</th><th>Status</th></tr></thead><tbody>{data.recommendations.map(company=><tr key={company._id}><td><Link className="table-primary" to={`/empresas/${company._id}`}>{company.name}</Link></td><td>{company.segment}</td><td>{[company.city,company.state].filter(Boolean).join(' / ')||'—'}</td><td><strong className="score">{company.potential}%</strong></td><td><StatusBadge status={company.status}/></td></tr>)}</tbody></table></div>:<EmptyState title="Sua fila está limpa" text="Cadastre a primeira empresa para começar a prospectar." action={<Link className="button button--secondary" to="/empresas/nova">Cadastrar empresa</Link>}/>}</section></div>;
}
