import { useCallback, useEffect, useState } from 'react';
import { Building2, CalendarDays, CircleDollarSign, CreditCard, FileCheck2, FileClock, Plus, Rocket, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';
import { ErrorState, LoadingState, EmptyState } from '../components/PageState.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { currency } from '../utils/currency.js';
import { useAuth } from '../contexts/AuthContext.jsx';

export function DashboardPage(){
  const{admin}=useAuth();const[data,setData]=useState(null),[error,setError]=useState('');const load=useCallback(()=>{setError('');api('/dashboard').then(setData).catch(e=>setError(e.message));},[]);useEffect(load,[load]);
  if(!data&&!error)return <LoadingState/>;if(error)return <ErrorState message={error} onRetry={load}/>;
  const cards=[[data.metrics.companies,'Empresas',Building2,'oportunidades'],[data.metrics.preparingSites,'Em produção',FileClock,'fluxo ativo'],[data.metrics.publishedSites,'Publicados',FileCheck2,'demonstrações'],[currency(data.metrics.monthlyRevenue),'Receita mensal',CircleDollarSign,'recorrente']];
  const today=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'}).format(new Date());
  return <div className="page dashboard-page"><div className="dashboard-welcome"><div><h1>Bem-vindo, <span>{admin?.name?.split(' ')[0]||'Felipe'}.</span></h1><p>Aqui está o resumo do XFia Studio hoje.</p></div><div className="dashboard-date"><CalendarDays/>{today}</div></div>
    <section className="metric-grid dashboard-metrics">{cards.map(([value,label,Icon,hint])=><article className="metric-card" key={label}><div><span>{label}</span><strong className={typeof value==='string'?'metric-money':''}>{value}</strong><small><TrendingUp/> {hint}</small></div><span className="metric-icon"><Icon/></span></article>)}</section>
    <div className="dashboard-main-grid"><section className="panel performance-panel"><div className="panel-heading"><div><span className="eyebrow">Performance</span><h2>Produção de sites</h2><p>Visão geral da operação no período.</p></div><span>Este mês</span></div><div className="performance-total"><strong>{data.metrics.preparingSites+data.metrics.publishedSites}</strong><span>projetos acompanhados</span></div><div className="dashboard-chart"><div className="chart-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 700 230" preserveAspectRatio="none" aria-label="Evolução visual da produção"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity=".42"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d="M0 205 C70 160 92 145 145 157 S215 92 270 125 S360 180 410 106 S490 38 535 82 S612 153 700 74 L700 230 L0 230Z"/><path className="chart-line" d="M0 205 C70 160 92 145 145 157 S215 92 270 125 S360 180 410 106 S490 38 535 82 S612 153 700 74"/><circle cx="700" cy="74" r="6"/></svg></div><div className="performance-footer"><div><small>Alto potencial</small><strong>{data.metrics.highPotential}</strong></div><div><small>Clientes ativos</small><strong>{data.metrics.activeClients}</strong></div><div><small>Receita de criação</small><strong>{currency(data.metrics.creationRevenue)}</strong></div></div></section>
      <div className="dashboard-side"><section className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">Prioridades</span><h2>Empresas recomendadas</h2></div><Link to="/empresas">Ver todas</Link></div>{data.recommendations.length?<div className="activity-list">{data.recommendations.slice(0,5).map(company=><Link to={`/empresas/${company._id}`} key={company._id}><span><Building2/></span><div><strong>{company.name}</strong><small>{company.segment}</small></div><b>{company.potential}%</b></Link>)}</div>:<EmptyState title="Sua fila está limpa" text="Cadastre a primeira empresa."/>}</section>
        <section className="panel quick-panel"><span className="eyebrow">Acesso rápido</span><div><Link to="/empresas/nova"><Building2/><small>Nova empresa</small></Link><Link to="/sites"><Rocket/><small>Sites</small></Link><Link to="/clientes"><Users/><small>Clientes</small></Link><Link to="/mensalidades"><CreditCard/><small>Mensalidades</small></Link></div></section></div>
    </div>
    <section className="panel dashboard-table"><div className="panel-heading"><div><h2>Fila comercial</h2><p>Empresas priorizadas por potencial e estágio.</p></div><Link className="button button--primary" to="/empresas/nova"><Plus/>Nova empresa</Link></div>{data.recommendations.length?<div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Segmento</th><th>Local</th><th>Potencial</th><th>Status</th></tr></thead><tbody>{data.recommendations.map(company=><tr key={company._id}><td><Link className="table-primary" to={`/empresas/${company._id}`}>{company.name}</Link></td><td>{company.segment}</td><td>{[company.city,company.state].filter(Boolean).join(' / ')||'—'}</td><td><strong className="score">{company.potential}%</strong></td><td><StatusBadge status={company.status}/></td></tr>)}</tbody></table></div>:null}</section>
  </div>;
}
