import { useCallback,useEffect,useState } from 'react';
import { CheckCircle2,Plus } from 'lucide-react';
import { api } from '../services/api.js';
import { currency,dateBR } from '../utils/currency.js';
import { EmptyState,ErrorState,LoadingState } from '../components/PageState.jsx';

const month=new Date().toISOString().slice(0,7);const initial={clientId:'',amount:50,dueDate:`${month}-10`,referenceMonth:month,status:'pendente',notes:''};
export function SubscriptionsPage(){
  const[data,setData]=useState(null),[clients,setClients]=useState([]),[form,setForm]=useState(initial),[show,setShow]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=useCallback(()=>Promise.all([api('/subscriptions'),api('/clients')]).then(([subscriptions,customers])=>{setData(subscriptions);setClients(customers.items)}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
  const chooseClient=id=>{const client=clients.find(item=>item._id===id);setForm({...form,clientId:id,amount:client?.monthlyFee??50})};
  const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await api('/subscriptions',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});setForm(initial);setShow(false);load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const pay=async item=>{try{const updated=await api(`/subscriptions/${item._id}`,{method:'PUT',body:JSON.stringify({status:'pago'})});setData(current=>({...current,items:current.items.map(row=>row._id===updated._id?updated:row)}))}catch(e){setError(e.message)}};
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Financeiro</span><h1>Mensalidades</h1><p>Controle manual de vencimentos e pagamentos.</p></div><button className="button button--primary" onClick={()=>setShow(!show)}><Plus size={18}/>Nova mensalidade</button></div>{show&&<form className="panel client-form" onSubmit={submit}><label className="span-2">Cliente<select required value={form.clientId} onChange={e=>chooseClient(e.target.value)}><option value="">Selecione</option>{clients.filter(c=>c.status==='ativo').map(client=><option key={client._id} value={client._id}>{client.companyId?.name}</option>)}</select></label><label>Valor<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Vencimento<input type="date" required value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Mês de referência<input type="month" required value={form.referenceMonth} onChange={e=>setForm({...form,referenceMonth:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>pendente</option><option>pago</option><option>cancelado</option></select></label><label className="span-2">Observações<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="button button--secondary" onClick={()=>setShow(false)}>Cancelar</button><button className="button button--primary" disabled={saving}>{saving?'Salvando...':'Cadastrar'}</button></div></form>}{error&&<ErrorState message={error} onRetry={load}/>} {!data&&!error?<LoadingState/>:data?.items.length?<section className="panel"><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Referência</th><th>Vencimento</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{data.items.map(item=><tr key={item._id}><td><strong>{item.clientId?.companyId?.name}</strong></td><td>{item.referenceMonth}</td><td>{dateBR(item.dueDate)}</td><td>{currency(item.amount)}</td><td><span className={`payment-status payment-status--${item.status}`}>{item.status}</span></td><td>{item.status!=='pago'&&item.status!=='cancelado'&&<button className="pay-button" onClick={()=>pay(item)}><CheckCircle2/>Marcar como pago</button>}</td></tr>)}</tbody></table></div></section>:data&&<section className="panel"><EmptyState title="Nenhuma mensalidade" text="Cadastre o primeiro vencimento de um cliente ativo."/></section>}</div>;
}
